### ISSUE TITLE
Question on BREAKOUT-specific

### ISSUE THREAD

**Issue by Andimeo** [wetliu/dqn_pytorch#1]
Hi,

Thanks for your great implementation. I noticed that on L119 in dqn.py there is a FIRE action for BREAKOUT specifically. I know that for BREAKOUT we have to hit FIRE every time we lost a life. But from some other discussions, I see that there's a saying that the fact above should be figured out by the model itself.

So I'm just wondering if you have done the experiments by any chance. Is it easy to learn the FIRE action? How many steps more do we need to achieve that? 

Another thought is that if it's easy, why do we have a wrapper called FireResetWrapper? I'd like to hear your thoughts on this too. Looking forward to your reply. Thank you!

**Comment by weitliu** [comment]
Thank you for your questions. The "fire" action taken from L119 is as you mentioned simply to initialize the game, then the no-op actions kick in to collect the frames. For breakout, this "fire" action is very simple and should not be a big issue. I haven't experimented that but "fire" is not an essential action for breakout so I don't expect it to take long. However, the agent may simply not "fire" in order to avoid losing points (but not getting points of course). In that case, the reward may have to be adjusted accordingly. 

The FireResetWrapper should follow the same logic for forcing the game to really "start."
